server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=1
            - id: user-auth
              uri: lb://user-service
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=1

            - id: book-service
              uri: lb://book-service
              predicates:
                - Path=/api/books/**
              filters:
                - StripPrefix=1
            - id: borrow-service
              uri: lb://borrow-service
              predicates:
                - Path=/api/borrows/**
              filters:
                - StripPrefix=1
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: "http://localhost:5173"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret: 38792F4A215E5C6B1484C2F987D651E84B1F83015E7C5784C5976A3D4B6C9B0F
