server:
  port: 8082

spring:
  application:
    name: book-service

  datasource:
    url: jdbc:mysql://localhost:3306/lms
    username: root
    password: qwer1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

